project:
  type: website
  output-dir: _site
  execute-dir: project

  render:
    - index.ipynb
    - microscopes/*.qmd

  resources:
    - "outputs/**"

metadata-files:
  - _navbar.yml

website:
  title: "Quality Assurance Laser Power Measurements"

  page-footer:
    center: "Generated automatically with Quarto and GitHub Actions"

format:
  html:
    theme: journal
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false
  error: false
  