project:
  type: website
  output-dir: _site
  execute-dir: project

  render:
    - index.ipynb
    - microscopes/*.qmd

  resources:
    - "outputs/**"

website:
  title: "Quality Assurance Laser Power Measurements"

  navbar:
    left:
      - href: index.html
        text: Home
      - href: microscopes/index.qmd
        text: Microscopes

  sidebar:
    - title: "Microscopes"
      contents: microscopes

  page-footer:
    center: "Generated automatically with Quarto and GitHub Actions"

format:
  html:
    theme: journal
    toc: true

execute:
  echo: false
  warning: false